version: "3.7"
services:
  mysql-service:
    image: mysql:5.7
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_example
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service

networks:
  spring-boot-mysql-network:
    driver: bridge